import fs from "node:fs/promises";
import path from "node:path";

/**
 * Completeness / anti-fake STATIC analyzer.
 *
 * Detects work an AI builder FAKED or left half-done — the #1 vibecoder gap that
 * functional-QA competitors never check. It reads source files and flags, with
 * file:line evidence + an honest confidence + a plain-English explanation, things
 * like stubbed bodies, mock data served as real, placeholder copy, dead UI, and
 * wiring gaps (env vars referenced but never declared).
 *
 * Design doctrine: PRECISION over recall. Every detector is scoped narrowly so a
 * finished, real codebase stays near-zero. Confidence is tagged honestly — a bare
 * `// TODO` is medium; `throw new Error("not implemented")` inside a handler is
 * high; `lorem ipsum` shipped in a page is high.
 *
 * Pure Node built-ins. No dependencies. Run via `node --experimental-strip-types`.
 */

export type CompletenessFinding = {
  id: string;
  kind: string;
  severity: "high" | "medium" | "low";
  confidence: "high" | "medium" | "low";
  file: string; // repo-relative
  line: number; // 1-based
  snippet: string; // trimmed offending line
  explain: string; // one sentence a non-developer understands
};

// Directories we never descend into. Build output, deps, and VCS internals.
const SKIP_DIRS = new Set([
  "node_modules", ".git", ".next", ".vercel", "dist", "build", "out", "coverage",
  ".turbo", ".cache", ".expo", "ios", "android", ".venv", "venv", "__pycache__",
  ".svelte-kit", ".nuxt", ".astro", "storybook-static",
]);

// Source files we look inside.
const SOURCE_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".vue", ".svelte", ".astro"]);

// JS/TS-family extensions where code-structural detectors (handlers, returns) apply.
const SCRIPT_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);

// Markup-bearing extensions where dead-UI / placeholder-content detectors apply.
const MARKUP_EXTENSIONS = new Set([".tsx", ".jsx", ".vue", ".svelte", ".astro", ".html", ".htm"]);

const MAX_FILES = 6000;
const MAX_FILE_BYTES = 1_500_000; // skip huge generated/minified blobs
const MAX_LINE_LENGTH = 2000; // a longer line is almost certainly minified — skip it

type WalkResult = { files: string[]; truncated: boolean };

/**
 * A test/spec/fixture/mock file legitimately contains stubs, mocks, and lorem.
 * We exclude these from the detectors so we don't punish real test scaffolding.
 * A mock module IMPORTED by runtime code is still flagged — at the import site,
 * not inside the mock itself.
 */
function isTestOrSpecFile(relPath: string): boolean {
  const base = path.basename(relPath).toLowerCase();
  const parts = relPath.toLowerCase().split(/[\\/]/);
  if (parts.includes("__tests__") || parts.includes("__mocks__") || parts.includes("__fixtures__")) return true;
  if (parts.includes("e2e") || parts.includes("cypress")) return true;
  if (/\.(test|spec)\.[cm]?[jt]sx?$/.test(base)) return true;
  if (/\.stories\.[cm]?[jt]sx?$/.test(base)) return true;
  if (base.endsWith(".d.ts")) return true; // type declarations have empty bodies by design
  return false;
}

/**
 * Generated / bundled output (esbuild, webpack, tsc, codegen) legitimately
 * contains inlined literals, minified handlers, and banner-marked stubs. Scanning
 * it produces false positives that say nothing about whether the AUTHOR faked
 * work. We skip a file when its first lines carry a generated banner or an obvious
 * bundler runtime signature. Conservative: only the top of the file is inspected.
 */
function looksGenerated(content: string): boolean {
  const head = content.slice(0, 600);
  if (/(^|\n)\s*(?:\/\/|\/\*|\*|#)\s*(?:@?generated\b|GENERATED by|auto-?generated|DO NOT EDIT|this file is generated|code generated)/i.test(head)) {
    return true;
  }
  // esbuild / webpack / rollup runtime prologue.
  if (/\bvar __(?:esm|commonJS|toESM|export|defProp|getOwnPropNames)\b/.test(head)) return true;
  if (/\b__webpack_require__\b|\b__webpack_modules__\b/.test(head)) return true;
  if (/\/\*\*?\s*@license|\bsourceMappingURL=/.test(head) && content.length > 30_000) return true;
  return false;
}

async function walk(rootDir: string): Promise<WalkResult> {
  const files: string[] = [];
  const queue: string[] = [rootDir];
  let truncated = false;

  while (queue.length > 0) {
    const dir = queue.shift()!;
    let entries;
    try {
      entries = await fs.readdir(dir, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const entry of entries) {
      if (files.length >= MAX_FILES) {
        truncated = true;
        break;
      }
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!SKIP_DIRS.has(entry.name) && !entry.name.startsWith(".git")) {
          queue.push(fullPath);
        }
      } else if (entry.isFile()) {
        const ext = path.extname(entry.name).toLowerCase();
        if (SOURCE_EXTENSIONS.has(ext)) files.push(fullPath);
      }
    }
    if (truncated) break;
  }
  return { files: files.sort(), truncated };
}

// --------------------------------------------------------------------------
// Lightweight per-line classification so we don't fire string/comment-only
// patterns inside the wrong context. Not a full parser — deliberately cheap and
// conservative; when unsure we err toward NOT flagging.
// --------------------------------------------------------------------------

type LineInfo = {
  raw: string;
  trimmed: string;
  codeOnly: string; // line with comment runs blanked, for code-structure checks
  isCommentLine: boolean; // line is wholly (or starts as) a comment
};

/**
 * Pre-process a file into per-line info with a running block-comment state. We
 * blank comment runs for the "codeOnly" view so structural detectors don't trip
 * on commented-out code, while the comment-marker detectors read the raw line.
 */
function analyzeLines(content: string): LineInfo[] {
  const lines = content.split(/\r?\n/);
  const out: LineInfo[] = [];
  const state = { inBlock: false };
  for (const raw of lines) {
    const trimmed = raw.trim();
    let codeOnly = "";
    let isCommentLine = false;
    if (state.inBlock) {
      isCommentLine = true;
      const end = raw.indexOf("*/");
      if (end !== -1) {
        state.inBlock = false;
        codeOnly = stripInlineComments(raw.slice(end + 2), state);
        if (codeOnly.trim().length > 0) isCommentLine = false;
      } else {
        codeOnly = "";
      }
    } else {
      codeOnly = stripInlineComments(raw, state);
      const c = codeOnly.trim();
      if (c.length === 0 && trimmed.length > 0) isCommentLine = true;
      if (trimmed.startsWith("*") && !c) isCommentLine = true;
    }
    out.push({ raw, trimmed, codeOnly, isCommentLine });
  }
  return out;
}

/**
 * Remove // line comments and block-comment runs from a single line. Naive about
 * strings, but codeOnly is only used for coarse structural matches where a
 * false-blank is harmless. Sets state.inBlock if a block comment opens unclosed.
 */
function stripInlineComments(line: string, state: { inBlock: boolean }): string {
  let result = "";
  let i = 0;
  let inStr: string | null = null;
  while (i < line.length) {
    const ch = line[i];
    const next = line[i + 1];
    if (inStr) {
      result += ch;
      if (ch === "\\") { result += next ?? ""; i += 2; continue; }
      if (ch === inStr) inStr = null;
      i += 1;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") { inStr = ch; result += ch; i += 1; continue; }
    if (ch === "/" && next === "/") break; // rest is a line comment
    if (ch === "/" && next === "*") {
      const close = line.indexOf("*/", i + 2);
      if (close === -1) { state.inBlock = true; break; }
      i = close + 2;
      result += " ";
      continue;
    }
    result += ch;
    i += 1;
  }
  return result;
}

// --------------------------------------------------------------------------
// Finding accumulator with stable, de-duped ids.
// --------------------------------------------------------------------------
class Findings {
  private list: CompletenessFinding[] = [];
  private seen = new Set<string>();
  private counters: Record<string, number> = {};

  add(
    kind: string,
    severity: CompletenessFinding["severity"],
    confidence: CompletenessFinding["confidence"],
    file: string,
    line: number,
    snippet: string,
    explain: string,
  ) {
    const dedupeKey = `${kind}|${file}|${line}`;
    if (this.seen.has(dedupeKey)) return;
    this.seen.add(dedupeKey);
    this.counters[kind] = (this.counters[kind] ?? 0) + 1;
    const id = `CMP-${kind.toUpperCase().replace(/[^A-Z0-9]+/g, "-")}-${String(this.counters[kind]).padStart(3, "0")}`;
    this.list.push({ id, kind, severity, confidence, file, line, snippet: snippet.trim().slice(0, 200), explain });
  }

  all(): CompletenessFinding[] {
    return this.list
      .slice()
      .sort((a, b) => (a.file === b.file ? a.line - b.line : a.file < b.file ? -1 : 1));
  }
}

// ==========================================================================
// DETECTORS — each is pure and independent.
// ==========================================================================

// --- Detector 1: stub / not-implemented throw bodies -----------------------
const NOT_IMPL_THROW = /\bthrow\s+new\s+\w*Error\s*\(\s*[`'"]([^`'"]*)[`'"]/i;
const NOT_IMPL_TEXT = /\b(not[\s_-]?implemented|unimplemented|notimplemented|todo[:\s]?implement|implement\s+me|to\s+be\s+implemented|coming\s+soon)\b/i;

function detectStubBodies(rel: string, lines: LineInfo[], handlerLines: Set<number>, fb: Findings) {
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].codeOnly.match(NOT_IMPL_THROW);
    if (m && NOT_IMPL_TEXT.test(m[1])) {
      const inHandler = handlerLines.has(i);
      fb.add(
        "stub-throw",
        "high",
        inHandler ? "high" : "medium",
        rel, i + 1, lines[i].trimmed,
        "This function is a stub that throws \"not implemented\" instead of doing real work.",
      );
    }
  }
}

// --- Detector 2: TODO / FIXME / placeholder markers in comments -------------
const TODO_MARKER = /(^|[^A-Za-z])(TODO|FIXME|HACK|XXX|STUB|WIP)\b[:\s-]?(.*)$/;

function detectTodoMarkers(rel: string, lines: LineInfo[], fb: Findings) {
  for (let i = 0; i < lines.length; i++) {
    const li = lines[i];
    const looksLikeComment =
      li.isCommentLine || li.trimmed.startsWith("//") || li.trimmed.startsWith("*") || li.trimmed.startsWith("{/*") || li.trimmed.startsWith("<!--");
    if (!looksLikeComment) continue;

    // Strip the leading comment punctuation so we can require the marker to be the
    // FIRST token — real action markers read "// TODO: x" / "* FIXME y", whereas
    // section dividers ("// --- Detector 2: TODO / FIXME markers ---") and prose
    // that merely mentions TODO mid-sentence are not actual unfinished-work items.
    const body = li.trimmed
      .replace(/^<!--\s*/, "")
      .replace(/^\{\/\*\s*/, "")
      .replace(/^\/\/+\s*/, "")
      .replace(/^\/\*+\s*/, "")
      .replace(/^\*+\s*/, "")
      .trim();
    // Skip ASCII-art / section-divider comment lines.
    if (/^[-=*_#~]{3,}/.test(body) || /-{3,}\s*Detector/i.test(li.trimmed)) continue;
    const lead = body.match(/^(TODO|FIXME|HACK|XXX|STUB|WIP)\b[:\s-]?(.*)$/);
    if (!lead) continue;
    const tag = lead[1].toUpperCase();
    const rest = (lead[2] || "").trim().replace(/-->.*$/, "").replace(/\*\/.*$/, "").trim();
    const strong = tag === "FIXME" || tag === "HACK" || tag === "XXX";
    fb.add(
      "todo-marker",
      strong ? "medium" : "low",
      strong ? "high" : "medium",
      rel, i + 1, li.trimmed,
      rest
        ? `A developer left a ${tag} note here meaning this code is unfinished: "${rest.slice(0, 80)}".`
        : `A developer left a ${tag} marker here, meaning this code was never finished.`,
    );
  }
}

// --- Detector 3: console.log-only handler bodies ---------------------------
const HANDLER_DECL =
  /\b(?:async\s+)?function\s+(handle\w+|on[A-Z]\w*|submit\w*|\w*Handler)\s*\(|\b(?:const|let)\s+(handle\w+|on[A-Z]\w*|\w*Handler)\s*=\s*(?:async\s*)?\(/;

function detectLogOnlyBodies(rel: string, lines: LineInfo[], fb: Findings) {
  for (let i = 0; i < lines.length; i++) {
    const decl = lines[i].codeOnly.match(HANDLER_DECL);
    if (!decl) continue;
    const body = collectBraceBody(lines, i);
    if (!body || body.statements.length === 0) continue;
    const onlyLogs = body.statements.every((s) => s === "" || /^console\.(log|debug|info|warn|error)\s*\(/.test(s) || /^return\b/.test(s));
    const hasLog = body.statements.some((s) => /^console\./.test(s));
    if (onlyLogs && hasLog && body.statements.filter((s) => s !== "" && !/^return\s*;?$/.test(s)).every((s) => /^console\./.test(s))) {
      const name = decl[1] || decl[2] || "handler";
      fb.add(
        "log-only-handler",
        "medium",
        "medium",
        rel, i + 1, lines[i].trimmed,
        `The "${name}" handler only logs to the console — it doesn't actually do anything.`,
      );
    }
  }
}

/**
 * From a line that opens a `{ ... }` body, collect the trimmed `;`-separated
 * statements inside the first balanced brace group. Bounded scan. Returns null
 * if we can't confidently find a single balanced body.
 */
function collectBraceBody(lines: LineInfo[], startIdx: number): { statements: string[]; endIdx: number } | null {
  let depth = 0;
  let started = false;
  const statements: string[] = [];
  let buffer = "";
  const MAX_SCAN = 60;
  for (let i = startIdx; i < lines.length && i < startIdx + MAX_SCAN; i++) {
    const code = lines[i].codeOnly;
    for (let j = 0; j < code.length; j++) {
      const ch = code[j];
      if (ch === "{") {
        depth += 1;
        if (depth === 1 && !started) { started = true; continue; }
      } else if (ch === "}") {
        depth -= 1;
        if (depth === 0 && started) {
          if (buffer.trim()) statements.push(buffer.trim());
          return { statements, endIdx: i };
        }
      }
      if (started && depth >= 1) {
        if (ch === ";") { statements.push(buffer.trim()); buffer = ""; }
        else buffer += ch;
      }
    }
    if (started) buffer += " ";
  }
  return null;
}

// --- Detector 4: faked/mock data served as real ----------------------------
const RESPONSE_JSON_CALL = /\b(?:res|reply|response|ctx|c)\s*\.\s*(?:json|send)\s*\(\s*(\[|\{)?/;
const FRAMEWORK_JSON_CALL = /\b(?:NextResponse|Response)\s*\.\s*json\s*\(\s*(\[|\{)?/;
const STATUS_THEN_JSON = /\b(?:res|reply|response)\s*\.\s*status\s*\([^)]*\)\s*\.\s*(?:json|send)\s*\(\s*(\[|\{)?/;
const MOCK_IMPORT =
  /(?:\bfrom\s*|\brequire\s*\(\s*)['"]([^'"]*(?:^|\/)(?:mock|mocks|fake|fakes|sample|samples|dummy|seed|seeds|stub|stubs|placeholder)(?:-data|Data)?[^'"]*)['"]/i;

function looksLikeApiHandler(rel: string, content: string): boolean {
  const p = rel.toLowerCase();
  if (/(^|[\\/])api[\\/]/.test(p)) return true;
  if (/(^|[\\/])route\.[cm]?[jt]sx?$/.test(p)) return true;
  if (/\bexport\s+(?:async\s+)?function\s+(GET|POST|PUT|PATCH|DELETE)\b/.test(content)) return true;
  if (/\b(?:app|router)\.(get|post|put|patch|delete)\s*\(/.test(content)) return true;
  if (/\bNextResponse\b/.test(content)) return true;
  if (/\bcreateServer\b/.test(content) && /\bres(?:ponse)?\b/.test(content)) return true;
  return false;
}

/**
 * Starting at startIdx, gather the literal that the response call returns and
 * decide whether it is a RICH hardcoded data payload (array of objects, or an
 * object with several data-ish keys carrying real string/number values) versus a
 * trivial `{ ok: true }` / `[]` / `{ error: ... }` status response.
 */
function isHardcodedDataPayload(lines: LineInfo[], startIdx: number, callLineCol: number): { rich: boolean } {
  let depth = 0;
  let started = false;
  let text = "";
  let startCol = callLineCol;
  for (let i = startIdx; i < lines.length && i < startIdx + 40; i++) {
    const code = lines[i].codeOnly;
    for (let j = i === startIdx ? startCol : 0; j < code.length; j++) {
      const ch = code[j];
      if (ch === "[" || ch === "{") { depth += 1; started = true; }
      if (started) text += ch;
      if (ch === "]" || ch === "}") {
        depth -= 1;
        if (depth <= 0 && started) { i = lines.length; break; }
      }
      // Bail if the very first non-space char after the paren isn't a literal opener.
      if (!started && ch !== " " && ch !== "(" && ch !== ")") {
        if (ch !== "[" && ch !== "{") return { rich: false };
      }
    }
    if (started) text += " ";
    startCol = 0;
  }
  if (!started) return { rich: false };
  const objectCount = (text.match(/\{[^{}]*[A-Za-z_$][\w$]*\s*:/g) || []).length;
  const keyCount = (text.match(/[A-Za-z_$][\w$]*\s*:/g) || []).length;
  const hasStringValues = /:\s*['"][^'"]{2,}['"]/.test(text) || /:\s*\d{2,}/.test(text);
  const isArrayOfObjects = /^\s*\[\s*\{/.test(text) && objectCount >= 1;
  const trivialStatus = /^\s*\{\s*(?:ok|success|error|message|status|deleted|updated|created)\s*:/.test(text) && keyCount <= 2;
  const rich = !trivialStatus && ((isArrayOfObjects && hasStringValues) || (keyCount >= 3 && objectCount >= 1 && hasStringValues));
  return { rich };
}

function detectFakeData(rel: string, lines: LineInfo[], content: string, fb: Findings) {
  // (b) mock/sample import in runtime code — high signal regardless of file type.
  for (let i = 0; i < lines.length; i++) {
    const mi = lines[i].codeOnly.match(MOCK_IMPORT);
    if (mi) {
      fb.add(
        "mock-import",
        "high",
        "medium",
        rel, i + 1, lines[i].trimmed,
        `This live code imports from "${mi[1]}", a mock/sample data module that shouldn't ship as real functionality.`,
      );
    }
  }

  // (a) hardcoded literal returned as an API response — only in handler-ish files.
  if (!looksLikeApiHandler(rel, content)) return;
  for (let i = 0; i < lines.length; i++) {
    const code = lines[i].codeOnly;
    const match = code.match(RESPONSE_JSON_CALL) || code.match(FRAMEWORK_JSON_CALL) || code.match(STATUS_THEN_JSON);
    if (!match) continue;
    // Require this to be a response being sent (returned or a clear send call).
    const col = (match.index ?? 0) + match[0].length - (match[1] ? 1 : 0);
    const { rich } = isHardcodedDataPayload(lines, i, Math.max(0, col));
    if (rich) {
      fb.add(
        "hardcoded-api-data",
        "high",
        "medium",
        rel, i + 1, lines[i].trimmed,
        "This API endpoint returns hardcoded sample data baked into the code instead of reading from a real database.",
      );
    }
  }
}

// --- Detector 5: placeholder content ---------------------------------------
const LOREM = /\blorem\s+ipsum\b/i;
const PLACEHOLDER_PHRASES =
  /\b(coming\s+soon|under\s+construction|your\s+text\s+here|placeholder\s+text|insert\s+(?:your\s+)?(?:text|content|name)\s+here|replace\s+this\s+(?:text|content)|example\s+domain|sample\s+(?:text|content)|content\s+goes\s+here|to\s+be\s+(?:added|written|determined))\b/i;
const PLACEHOLDER_EMAIL =
  /\b[A-Za-z0-9._%+-]+@(?:example|sample|domain|yourdomain|youremail|acme|foo|bar)\.(?:com|org|net|io)\b/i;
const PLACEHOLDER_URL = /\bhttps?:\/\/(?:www\.)?(?:example\.(?:com|org|net)|yourdomain\.\w+|your-site\.\w+)/i;

function detectPlaceholderContent(rel: string, lines: LineInfo[], fb: Findings) {
  const ext = path.extname(rel).toLowerCase();
  const isMarkup = MARKUP_EXTENSIONS.has(ext);

  // In plain script files, the words "lorem ipsum" / "placeholder" / "coming soon"
  // legitimately appear as DETECTOR RULES, config tables, or option lists inside
  // ordinary quoted strings. Treat such a match as real shipped CONTENT only when
  // it sits in a comment, a JSX text node, or a template literal (backticks) — the
  // places that actually render to a user. This kills the "an auditor flags its own
  // ruleset" false-positive class while keeping real page copy.
  const contentContext = (li: LineInfo): boolean => {
    if (isMarkup) return true; // markup strings/JSX text are user-facing content
    if (li.isCommentLine) return true;
    if (li.raw.includes("`")) return true; // template literal — likely rendered output
    if (/\{\/\*|^\s*</.test(li.trimmed)) return true; // JSX-ish
    return false;
  };

  for (let i = 0; i < lines.length; i++) {
    const li = lines[i];
    const raw = li.raw;

    if (LOREM.test(raw) && contentContext(li)) {
      fb.add("lorem-ipsum", "high", "high", rel, i + 1, li.trimmed,
        "This page still has placeholder \"lorem ipsum\" filler text instead of real content.");
      continue;
    }

    const pm = raw.match(PLACEHOLDER_PHRASES);
    if (pm && contentContext(li)) {
      const phrase = pm[0].toLowerCase();
      const strong = isMarkup || /example\s+domain|your\s+text\s+here|placeholder\s+text|content\s+goes\s+here/.test(phrase);
      fb.add("placeholder-content", strong ? "medium" : "low", strong ? "high" : "medium", rel, i + 1, li.trimmed,
        `This contains placeholder text ("${pm[0]}") that looks like it was never replaced with real content.`);
      continue;
    }

    // Placeholder emails / URLs — skip comment lines (often illustrative) and
    // never count *.test / *.local intentional test domains as fakes.
    if (!li.isCommentLine) {
      const emailM = raw.match(PLACEHOLDER_EMAIL);
      if (emailM) {
        fb.add("placeholder-email", "low", "medium", rel, i + 1, li.trimmed,
          `This uses a placeholder email address (${emailM[0]}) that isn't a real contact.`);
      }
      const urlM = raw.match(PLACEHOLDER_URL);
      if (urlM) {
        fb.add("placeholder-url", "low", "medium", rel, i + 1, li.trimmed,
          `This points at a placeholder/example URL (${urlM[0].slice(0, 60)}) instead of a real destination.`);
      }
    }
  }
}

// --- Detector 6: dead UI (JSX/markup) --------------------------------------
const EMPTY_JSX_HANDLER =
  /\bon(Click|Submit|Change|Input|KeyDown|KeyUp|MouseDown|Press|Toggle|Focus|Blur)\s*=\s*\{\s*(?:async\s*)?\(\s*[^)]*\)\s*=>\s*\{\s*\}\s*\}/;
const NOOP_JSX_HANDLER =
  /\bon(Click|Submit|Change|Press)\s*=\s*\{\s*(?:\(\s*\)\s*=>\s*(?:undefined|null|void\s*0)|function\s*\(\s*\)\s*\{\s*\})\s*\}/;
const DEAD_HREF = /\bhref\s*=\s*(?:["'](#|javascript:void\(0\);?)["']|\{\s*["'](#)["']\s*\})/;
const ANCHOR_TAG = /<a\b[^>]*>/i;
const FORM_OPEN = /<form\b([^>]*)>/i;

function detectDeadUi(rel: string, lines: LineInfo[], fb: Findings) {
  const ext = path.extname(rel).toLowerCase();
  if (!MARKUP_EXTENSIONS.has(ext)) return;

  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i].raw;
    const code = lines[i].codeOnly && lines[i].codeOnly.trim() ? lines[i].codeOnly : raw;

    if (EMPTY_JSX_HANDLER.test(code) || NOOP_JSX_HANDLER.test(code)) {
      const which = (code.match(/\bon(\w+)\s*=/) || [, "handler"])[1];
      fb.add("dead-handler", "medium", "high", rel, i + 1, lines[i].trimmed,
        `This ${String(which).toLowerCase()} control has an empty handler, so interacting with it does nothing.`);
    }

    if (DEAD_HREF.test(code) && ANCHOR_TAG.test(raw)) {
      fb.add("dead-link", "low", "medium", rel, i + 1, lines[i].trimmed,
        "This link points to \"#\" (nowhere) — it looks clickable but goes nowhere.");
    }

    const fm = code.match(FORM_OPEN);
    if (fm) {
      const windowText = [code, lines[i + 1]?.raw ?? "", lines[i + 2]?.raw ?? "", lines[i + 3]?.raw ?? ""].join(" ");
      const hasHandler =
        /\bonSubmit\s*=/.test(windowText) ||
        /\baction\s*=\s*["'{][^"'}\s]+/.test(windowText) ||
        /\bhandleSubmit\b/.test(windowText);
      if (!hasHandler) {
        fb.add("unwired-form", "medium", "medium", rel, i + 1, lines[i].trimmed,
          "This form has no submit handler or action, so filling it out and submitting does nothing.");
      }
    }
  }
}

// --------------------------------------------------------------------------
// Handler-context line set, so stub throws inside handlers raise confidence.
// --------------------------------------------------------------------------
const HANDLER_SIG =
  /\bexport\s+(?:async\s+)?function\s+(?:GET|POST|PUT|PATCH|DELETE)\b|\b(?:app|router|server)\.(?:get|post|put|patch|delete|use|all)\s*\(|\b(?:async\s+)?function\s+\w*[Hh]andler\b|\baddEventListener\s*\(|\bcreateServer\s*\(/;

function handlerContextLines(lines: LineInfo[]): Set<number> {
  const set = new Set<number>();
  for (let i = 0; i < lines.length; i++) {
    if (HANDLER_SIG.test(lines[i].codeOnly)) {
      for (let j = i; j < Math.min(lines.length, i + 50); j++) set.add(j);
    }
  }
  return set;
}

// --------------------------------------------------------------------------
// Env wiring-gap detector (cross-file). Collect process.env / import.meta.env
// references, subtract keys declared in any .env* file + a runtime allowlist, and
// report each referenced-but-undeclared key once (at its first reference).
// --------------------------------------------------------------------------
const RUNTIME_PROVIDED_ENV = new Set([
  "NODE_ENV", "PORT", "CI", "HOME", "PATH", "PWD", "TZ", "USER", "SHELL", "LANG",
  "VERCEL", "VERCEL_ENV", "VERCEL_URL", "VERCEL_REGION", "VERCEL_GIT_COMMIT_SHA",
  "AWS_REGION", "AWS_LAMBDA_FUNCTION_NAME", "npm_package_version", "npm_lifecycle_event",
]);
const ENV_REF =
  /(?:process\.env\.([A-Z][A-Z0-9_]*)|process\.env\[\s*['"]([A-Z][A-Z0-9_]*)['"]\s*\]|import\.meta\.env\.([A-Z][A-Z0-9_]*))/g;

async function collectDeclaredEnv(repoPath: string): Promise<Set<string>> {
  const declared = new Set<string>();
  const candidates = [
    ".env", ".env.local", ".env.development", ".env.development.local",
    ".env.production", ".env.production.local", ".env.test",
    ".env.example", ".env.sample", ".env.template",
  ];
  for (const candidate of candidates) {
    let content;
    try {
      content = await fs.readFile(path.join(repoPath, candidate), "utf8");
    } catch {
      continue;
    }
    for (const line of content.split("\n")) {
      const m = line.match(/^\s*(?:export\s+)?([A-Z][A-Z0-9_]*)\s*=/);
      if (m) declared.add(m[1]);
    }
  }
  return declared;
}

type EnvRefSite = { file: string; line: number; snippet: string };

function collectEnvRefs(rel: string, lines: LineInfo[], into: Map<string, EnvRefSite>) {
  for (let i = 0; i < lines.length; i++) {
    const code = lines[i].codeOnly;
    if (!code.includes("process.env") && !code.includes("import.meta.env")) continue;
    ENV_REF.lastIndex = 0;
    let m: RegExpExecArray | null;
    while ((m = ENV_REF.exec(code)) !== null) {
      const key = m[1] || m[2] || m[3];
      if (!key) continue;
      if (!into.has(key)) into.set(key, { file: rel, line: i + 1, snippet: lines[i].trimmed });
    }
  }
}

async function anyEnvFileExists(repoPath: string): Promise<boolean> {
  const candidates = [".env", ".env.local", ".env.example", ".env.sample", ".env.template", ".env.production", ".env.development"];
  for (const c of candidates) {
    try {
      await fs.access(path.join(repoPath, c));
      return true;
    } catch {
      // keep checking
    }
  }
  return false;
}

// ==========================================================================
// PUBLIC ENTRYPOINT
// ==========================================================================
export async function scanCompleteness(repoPath: string): Promise<CompletenessFinding[]> {
  const resolved = path.resolve(repoPath);
  const fb = new Findings();

  let walked: WalkResult;
  try {
    walked = await walk(resolved);
  } catch {
    return [];
  }

  const declaredEnvPromise = collectDeclaredEnv(resolved);
  const envRefs = new Map<string, EnvRefSite>();

  for (const absFile of walked.files) {
    const rel = path.relative(resolved, absFile) || path.basename(absFile);
    if (isTestOrSpecFile(rel)) continue;

    let stat;
    try {
      stat = await fs.stat(absFile);
    } catch {
      continue;
    }
    if (stat.size > MAX_FILE_BYTES) continue;

    let content;
    try {
      content = await fs.readFile(absFile, "utf8");
    } catch {
      continue;
    }
    // Skip apparently-minified files (little newline density relative to length).
    if (content.length > 50_000 && content.split("\n").length < content.length / 400) continue;
    // Skip generated / bundled output — its inlined literals are not author fakes.
    if (looksGenerated(content)) continue;

    const lines = analyzeLines(content);
    for (const li of lines) {
      if (li.raw.length > MAX_LINE_LENGTH) (li as { codeOnly: string }).codeOnly = "";
    }

    const ext = path.extname(rel).toLowerCase();
    const isScript = SCRIPT_EXTENSIONS.has(ext);

    detectTodoMarkers(rel, lines, fb);
    detectPlaceholderContent(rel, lines, fb);
    detectDeadUi(rel, lines, fb);

    if (isScript) {
      const handlerLines = handlerContextLines(lines);
      detectStubBodies(rel, lines, handlerLines, fb);
      detectLogOnlyBodies(rel, lines, fb);
      detectFakeData(rel, lines, content, fb);
      collectEnvRefs(rel, lines, envRefs);
    }
  }

  // Env wiring gaps. Only flag undeclared keys. If the project ships no .env*
  // template at all, restrict to keys that clearly name a configurable secret/URL
  // (avoids noise on apps configured entirely via a host UI).
  const declaredEnv = await declaredEnvPromise;
  const hasAnyEnvFile = declaredEnv.size > 0 || (await anyEnvFileExists(resolved));
  for (const [key, site] of envRefs) {
    if (RUNTIME_PROVIDED_ENV.has(key)) continue;
    if (declaredEnv.has(key)) continue;
    const looksConfigurable =
      /(KEY|SECRET|TOKEN|URL|URI|DSN|PASSWORD|HOST|ENDPOINT|API|CLIENT_ID|PROJECT_ID|REGION|BUCKET|DATABASE|CONNECTION|WEBHOOK)/.test(key);
    if (!hasAnyEnvFile && !looksConfigurable) continue;
    fb.add(
      "env-wiring-gap",
      "medium",
      hasAnyEnvFile ? "high" : "medium",
      site.file, site.line, site.snippet,
      `The code reads a setting "${key}" that is never defined in any .env file, so this feature will be misconfigured at runtime.`,
    );
  }

  return fb.all();
}
