/**
 * Real executable test cards for the LaunchAudit platform itself.
 * Every card runs in a real browser against the deployed app — the platform
 * audits itself as its own first customer.
 */
import type { ExecutableTestCard } from "../executor.ts";

export const cards: ExecutableTestCard[] = [
  {
    id: "TC-LA-001",
    title: "Command center loads with campaign data rendered",
    category: "core_workflow",
    status: "ready",
    risk: "critical",
    goal: "A customer opening the command center sees their campaign, not a blank shell or a load error.",
    steps: ["Open the app root", "Wait for the campaign API render"],
    expectedEvidence: ["screenshot"],
    dataNeeds: [],
    acceptanceCriteria: "At least one metric card and one test card render from the API.",
    exec: [
      { action: "goto", path: "/" },
      { action: "wait", ms: 800 },
      { action: "expect_visible", selector: ".metric-card" },
      { action: "expect_visible", selector: ".test-card" },
    ],
  },
  {
    id: "TC-LA-002",
    title: "Sidebar navigation switches to Reports view",
    category: "core_workflow",
    status: "ready",
    risk: "high",
    goal: "Navigation is functional — clicking Reports shows the proof harness and hides campaign sections.",
    steps: ["Open root", "Click Reports in sidebar", "Verify proof harness visible"],
    expectedEvidence: ["screenshot"],
    dataNeeds: [],
    acceptanceCriteria: "Outperformance proof harness heading is visible after clicking Reports.",
    exec: [
      { action: "goto", path: "/" },
      { action: "wait", ms: 600 },
      { action: "click", selector: '[data-nav="reports"]' },
      { action: "wait", ms: 400 },
      { action: "expect_visible", selector: '[data-view="reports"] .scorecard-card, [data-view="reports"] #scorecard' },
      { action: "expect_url", contains: "#/reports" },
    ],
  },
  {
    id: "TC-LA-003",
    title: "Theme toggle flips to light and survives reload",
    category: "state_persistence",
    status: "ready",
    risk: "medium",
    goal: "User preference persists across sessions via localStorage.",
    steps: ["Open root", "Click theme toggle", "Reload", "Verify light theme still active"],
    expectedEvidence: ["screenshot"],
    dataNeeds: [],
    acceptanceCriteria: "html[data-theme=light] present after toggle AND after reload.",
    exec: [
      { action: "goto", path: "/" },
      { action: "wait", ms: 600 },
      { action: "click", selector: "#theme-toggle" },
      { action: "wait", ms: 300 },
      { action: "expect_visible", selector: 'html[data-theme="light"] body' },
      { action: "reload" },
      { action: "wait", ms: 600 },
      { action: "expect_visible", selector: 'html[data-theme="light"] body' },
    ],
  },
  {
    id: "TC-LA-004",
    title: "Campaign API returns full contract",
    category: "api_contract",
    status: "ready",
    risk: "critical",
    goal: "The API that feeds everything returns 200 with the complete payload contract.",
    steps: ["GET /api/campaign", "Verify status and required keys"],
    expectedEvidence: ["network_log"],
    dataNeeds: [],
    acceptanceCriteria: "200 response containing campaign, test_cards, findings, repair_tasks, persistence.",
    exec: [
      { action: "expect_http_ok", path: "/api/campaign", jsonKeys: ["campaign", "test_cards", "findings", "repair_tasks", "persistence"] },
    ],
  },
  {
    id: "TC-LA-005",
    title: "Start campaign opens quickstart with real MCP command",
    category: "core_workflow",
    status: "ready",
    risk: "medium",
    goal: "Primary CTA gives the customer an actionable path, then closes cleanly.",
    steps: ["Open root", "Click Start campaign", "Verify MCP command shown", "Escape closes"],
    expectedEvidence: ["screenshot"],
    dataNeeds: [],
    acceptanceCriteria: "Modal opens containing the launchaudit MCP install command; Escape dismisses it.",
    exec: [
      { action: "goto", path: "/" },
      { action: "wait", ms: 600 },
      { action: "click", selector: "#start-campaign-btn" },
      { action: "wait", ms: 350 },
      { action: "expect_visible", selector: ".modal-backdrop.open .modal" },
      { action: "expect_text", selector: ".modal-code", contains: "claude mcp add launchaudit" },
      { action: "press", key: "Escape" },
    ],
  },
  {
    id: "TC-LA-006",
    title: "Mobile 390px renders without horizontal overflow",
    category: "responsive_visual",
    status: "ready",
    risk: "high",
    goal: "Customers on phones get a usable command center, not sideways scrolling.",
    steps: ["Set 390x844 viewport", "Open root", "Measure scrollWidth vs clientWidth"],
    expectedEvidence: ["screenshot"],
    dataNeeds: [],
    acceptanceCriteria: "documentElement.scrollWidth <= clientWidth at 390px.",
    exec: [
      { action: "set_viewport", width: 390, height: 844 },
      { action: "goto", path: "/" },
      { action: "wait", ms: 800 },
      { action: "expect_no_horizontal_overflow" },
    ],
  },
  {
    id: "TC-LA-007",
    title: "Page loads with zero console errors and no 5xx requests",
    category: "console_network",
    status: "ready",
    risk: "high",
    goal: "Clean console and network on load — the baseline of a professional product.",
    steps: ["Open root", "Navigate all six views", "Collect console + network"],
    expectedEvidence: ["network_log", "screenshot"],
    dataNeeds: [],
    acceptanceCriteria: "Zero console.error entries and zero 5xx responses across a full view walk.",
    exec: [
      { action: "goto", path: "/" },
      { action: "wait", ms: 700 },
      { action: "click", selector: '[data-nav="projects"]' },
      { action: "click", selector: '[data-nav="runner"]' },
      { action: "click", selector: '[data-nav="evidence"]' },
      { action: "click", selector: '[data-nav="reports"]' },
      { action: "click", selector: '[data-nav="models"]' },
      { action: "wait", ms: 500 },
      { action: "expect_console_clean" },
      { action: "expect_network_clean" },
    ],
  },
];
