/**
 * Bundle TypeScript API handlers into self-contained JS that Vercel's
 * function packager deploys without resolving anything.
 */
import { build } from "esbuild";

const entries: Array<[string, string]> = [
  ["server/api-src/campaign.ts", "api/campaign.js"],
  ["server/api-src/campaigns.ts", "api/campaigns.js"],
  ["server/api-src/grade.ts", "api/grade.js"],
  ["server/api-src/waitlist.ts", "api/waitlist.js"],
  ["server/api-src/monitor.ts", "api/monitor.js"],
  ["server/api-src/rescan-cron.ts", "api/rescan-cron.js"],
  ["server/api-src/crm-reconcile.ts", "api/crm-reconcile.js"],
  ["server/api-src/contact.ts", "api/contact.js"],
  ["server/api-src/checkout.ts", "api/checkout.js"],
  ["server/api-src/stripe-webhook.ts", "api/stripe-webhook.js"],
  ["server/api-src/order-status.ts", "api/order-status.js"],
  ["server/api-src/grade-order.ts", "api/grade-order.js"],
  ["server/api-src/runner/sync.ts", "api/runner/sync.js"],
  ["server/api-src/storage/register-artifact.ts", "api/storage/register-artifact.js"],
];

for (const [entry, outfile] of entries) {
  await build({
    entryPoints: [entry],
    outfile,
    bundle: true,
    platform: "node",
    target: "node20",
    format: "esm",
    banner: { js: "// GENERATED by scripts/build-api.ts — edit server/api-src/* instead.\nimport { createRequire as createNodeRequire } from 'node:module';\nconst require = createNodeRequire(import.meta.url);" },
    logLevel: "silent",
  });
  // Exercise module initialization, not just compilation: catches CJS/ESM runtime failures.
  await import(new URL(`../${outfile}`, import.meta.url).href);
  console.log(`bundled and load-checked ${entry} -> ${outfile}`);
}
