/**
 * Bundle TypeScript API handlers into self-contained JS that Vercel's
 * function packager deploys without resolving anything.
 */
import { build } from "esbuild";

const entries: Array<[string, string]> = [
  ["server/api-src/campaign.ts", "api/campaign.js"],
  ["server/api-src/campaigns.ts", "api/campaigns.js"],
  ["server/api-src/grade.ts", "api/grade.js"],
  ["server/api-src/runner/sync.ts", "api/runner/sync.js"],
  ["server/api-src/storage/register-artifact.ts", "api/storage/register-artifact.js"],
];

for (const [entry, outfile] of entries) {
  await build({
    entryPoints: [entry],
    outfile,
    bundle: true,
    platform: "node",
    target: "node20",
    format: "esm",
    banner: { js: "// GENERATED by scripts/build-api.ts — edit server/api-src/* instead." },
    logLevel: "silent",
  });
  console.log(`bundled ${entry} -> ${outfile}`);
}
