// GENERATED by scripts/build-api.ts — edit server/api-src/* instead.

// src/lib/instant-grade.ts
import net from "node:net";
function privateIp(ip) {
  if (net.isIPv4(ip)) {
    const [a, b] = ip.split(".").map(Number);
    return a === 10 || a === 127 || a === 0 || a === 169 && b === 254 || a === 172 && b >= 16 && b <= 31 || a === 192 && b === 168 || a === 100 && b >= 64 && b <= 127;
  }
  const x = ip.toLowerCase();
  return x === "::1" || x.startsWith("fc") || x.startsWith("fd") || x.startsWith("fe80") || x.startsWith("::ffff:127.") || x.startsWith("::ffff:10.") || x.startsWith("::ffff:192.168.");
}
function hostLooksPrivate(host) {
  const h = host.toLowerCase();
  const bad = ["localhost", "metadata.google.internal", "instance-data"];
  if (bad.includes(h) || h.endsWith(".internal") || h.endsWith(".local") || h.endsWith(".localhost")) return "private host";
  if (net.isIP(host) && privateIp(host)) return "private ip";
  return null;
}
function parseTargetUrl(input) {
  let raw = typeof input === "string" ? input.trim() : "";
  if (!raw) return { ok: false, error: "Provide a url." };
  if (raw.length > 2048) return { ok: false, error: "That URL is too long." };
  if (!/^https?:\/\//i.test(raw)) raw = "https://" + raw;
  let u;
  try {
    u = new URL(raw);
  } catch {
    return { ok: false, error: `Not a valid URL: ${raw}` };
  }
  if (u.protocol !== "http:" && u.protocol !== "https:") return { ok: false, error: "Only http/https URLs." };
  if (u.username || u.password) return { ok: false, error: "Credentials in the URL aren't allowed." };
  if (!u.hostname || !u.hostname.includes(".") && !net.isIP(u.hostname)) return { ok: false, error: "That doesn't look like a public hostname." };
  if (hostLooksPrivate(u.hostname)) return { ok: false, error: "That host isn't a public address we can scan." };
  return { ok: true, url: u };
}

// src/lib/checkout-input.ts
var AUDIT_TIERS = {
  single: { label: "Single Run", amountCents: 7900, priceEnv: "STRIPE_PRICE_AUDIT_SINGLE" },
  standard: { label: "Hosted Deep Audit", amountCents: 14900, priceEnv: "STRIPE_PRICE_AUDIT" },
  pro: { label: "Hosted Deep Audit \u2014 Pro", amountCents: 49900, priceEnv: "STRIPE_PRICE_AUDIT_PRO" }
};
var EMAIL_RE = /^[^@\s]+@[^@\s]+\.[^@\s]+$/;
function isAuditTier(value) {
  return value === "single" || value === "standard" || value === "pro";
}
function validateCheckoutInput(body) {
  const b = body && typeof body === "object" ? body : {};
  const parsed = parseTargetUrl(b.url);
  if (!parsed.ok) return { ok: false, error: parsed.error };
  const email = typeof b.email === "string" ? b.email.trim() : "";
  if (!email) return { ok: false, error: "Enter the email the report should go to." };
  if (email.length > 320 || !EMAIL_RE.test(email)) return { ok: false, error: "Enter a valid email." };
  const tier = b.tier ?? "single";
  if (!isAuditTier(tier)) return { ok: false, error: 'tier must be "single", "standard" or "pro".' };
  if (tier !== "single") return { ok: false, error: "Deep and Pro audits are quoted by hand. Use the contact form and we will reply with a scope and a price." };
  if (b.authorized !== true) return { ok: false, error: "Confirm that you own this site or are authorised to test it." };
  return { ok: true, value: { url: parsed.url.origin + (parsed.url.pathname === "/" ? "" : parsed.url.pathname), email, tier } };
}

// src/lib/stripe.ts
function encodeForm(obj, prefix = "", out = []) {
  for (const [k, v] of Object.entries(obj)) {
    if (v === void 0 || v === null) continue;
    const key = prefix ? `${prefix}[${k}]` : k;
    if (Array.isArray(v)) v.forEach((item, i) => typeof item === "object" && item ? encodeForm(item, `${key}[${i}]`, out) : out.push(`${encodeURIComponent(`${key}[${i}]`)}=${encodeURIComponent(String(item))}`));
    else if (typeof v === "object") encodeForm(v, key, out);
    else out.push(`${encodeURIComponent(key)}=${encodeURIComponent(String(v))}`);
  }
  return out.join("&");
}
async function stripeRequest(secretKey, path, body, opts = {}) {
  const r = await fetch(`https://api.stripe.com${path}`, {
    method: "POST",
    headers: {
      authorization: `Bearer ${secretKey}`,
      "content-type": "application/x-www-form-urlencoded",
      ...opts.idempotencyKey ? { "idempotency-key": opts.idempotencyKey } : {}
    },
    body: encodeForm(body)
  });
  const json = await r.json();
  if (!r.ok) throw new Error(json.error?.message || `Stripe ${path} failed (${r.status})`);
  return json;
}

// src/lib/rate-limit.ts
var buckets = /* @__PURE__ */ new Map();
var MAX_KEYS = 5e3;
function consumeAttempt(opts) {
  const now = opts.now ?? Date.now();
  const id = `${opts.scope}:${opts.key}`;
  let b = buckets.get(id);
  if (!b || b.resetAt <= now) {
    if (buckets.size >= MAX_KEYS) sweep(now);
    b = { count: 0, resetAt: now + opts.windowMs };
    buckets.set(id, b);
  }
  b.count += 1;
  if (b.count > opts.limit) return { ok: false, retryAfterSec: Math.max(1, Math.ceil((b.resetAt - now) / 1e3)) };
  return { ok: true, remaining: opts.limit - b.count };
}
function sweep(now) {
  for (const [k, v] of buckets) if (v.resetAt <= now) buckets.delete(k);
  if (buckets.size >= MAX_KEYS) buckets.clear();
}
function clientIp(headers) {
  const h = headers ?? {};
  const pick = (name) => {
    const v = h[name] ?? h[name.toLowerCase()];
    return Array.isArray(v) ? v[0] : v;
  };
  const xff = pick("x-forwarded-for");
  if (xff) return xff.split(",")[0].trim() || "unknown";
  return pick("x-real-ip")?.trim() || "unknown";
}

// server/api-src/checkout.ts
var SITE = "https://80-20.dev";
async function handler(req, res) {
  if (req.method !== "POST") {
    res.status(405).json({ error: "POST a JSON body { url, email, tier }." });
    return;
  }
  const rl = consumeAttempt({ scope: "checkout", key: clientIp(req.headers), limit: 6, windowMs: 10 * 6e4 });
  if (!rl.ok) {
    res.status(429).json({ error: `Too many checkout attempts. Try again in ${rl.retryAfterSec}s.` });
    return;
  }
  const input = validateCheckoutInput(req.body);
  if (!input.ok) {
    res.status(400).json({ error: input.error });
    return;
  }
  const { url, email, tier } = input.value;
  const secret = process.env.STRIPE_SECRET_KEY;
  if (!secret) {
    res.status(503).json({ error: "Ordering is temporarily unavailable (payments not configured)." });
    return;
  }
  const tierInfo = AUDIT_TIERS[tier];
  const priceId = process.env[tierInfo.priceEnv];
  const lineItem = priceId ? { price: priceId, quantity: 1 } : {
    quantity: 1,
    price_data: {
      currency: "usd",
      unit_amount: tierInfo.amountCents,
      product_data: { name: `80/20 Launch Audit \u2014 ${tierInfo.label}`, description: `Hosted deep audit of ${url}` }
    }
  };
  try {
    const session = await stripeRequest(secret, "/v1/checkout/sessions", {
      mode: "payment",
      // Card and Link only. Delayed-notification methods (Klarna, Afterpay, ACH, Cash App)
      // complete the session unpaid and settle later; the buyer would sit on the success
      // page with no report. The webhook handles async_payment_* anyway, belt and braces.
      payment_method_types: ["card", "link"],
      line_items: [lineItem],
      customer_email: email,
      metadata: { target_url: url, tier },
      payment_intent_data: { metadata: { target_url: url, tier } },
      success_url: `${SITE}/order/success?session_id={CHECKOUT_SESSION_ID}`,
      cancel_url: `${SITE}/#order`
    });
    res.status(200).json({ ok: true, url: session.url, session_id: session.id });
  } catch (e) {
    res.status(502).json({ error: e instanceof Error ? e.message : "Could not start checkout." });
  }
}
export {
  handler as default
};
