// GENERATED by scripts/build-api.ts — edit server/api-src/* instead.

// server/api-src/grade.ts
import dns from "node:dns/promises";
import net from "node:net";
var PENALTY = { critical: 22, high: 13, medium: 7, low: 3 };
function privateIp(ip) {
  if (net.isIPv4(ip)) {
    const [a, b] = ip.split(".").map(Number);
    return a === 10 || a === 127 || a === 0 || a === 169 && b === 254 || a === 172 && b >= 16 && b <= 31 || a === 192 && b === 168 || a === 100 && b >= 64 && b <= 127;
  }
  const x = ip.toLowerCase();
  return x === "::1" || x.startsWith("fc") || x.startsWith("fd") || x.startsWith("fe80") || x.startsWith("::ffff:127.") || x.startsWith("::ffff:10.") || x.startsWith("::ffff:192.168.");
}
async function assertPublic(host) {
  const bad = ["localhost", "metadata.google.internal", "instance-data"];
  if (bad.includes(host.toLowerCase()) || host.toLowerCase().endsWith(".internal") || host.toLowerCase().endsWith(".local")) throw new Error("private host");
  if (net.isIP(host)) {
    if (privateIp(host)) throw new Error("private ip");
    return;
  }
  const addrs = await dns.lookup(host, { all: true });
  if (!addrs.length || addrs.some((a) => privateIp(a.address))) throw new Error("resolves to private ip");
}
async function grab(url, opts = {}, ms = 8e3) {
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), ms);
  try {
    return await fetch(url, { ...opts, signal: ctrl.signal, redirect: "manual", headers: { "user-agent": "8020LaunchAudit-Grader/1.0", ...opts.headers || {} } });
  } finally {
    clearTimeout(t);
  }
}
async function handler(request, response) {
  if (request.method !== "POST") {
    response.status(405).json({ error: "POST a JSON body { url }." });
    return;
  }
  let raw = (request.body?.url || "").trim();
  if (!raw) {
    response.status(400).json({ error: "Provide a url." });
    return;
  }
  if (!/^https?:\/\//i.test(raw)) raw = "https://" + raw;
  let u;
  try {
    u = new URL(raw);
  } catch {
    response.status(400).json({ error: `Not a valid URL: ${raw}` });
    return;
  }
  if (u.protocol !== "http:" && u.protocol !== "https:") {
    response.status(400).json({ error: "Only http/https URLs." });
    return;
  }
  try {
    await assertPublic(u.hostname);
  } catch {
    response.status(400).json({ error: "That host isn't a public address we can scan." });
    return;
  }
  const findings = [];
  const passed = [];
  let html = "", main = null;
  try {
    main = await grab(u.toString());
    if (main.status >= 300 && main.status < 400 && main.headers.get("location")) {
      const loc = new URL(main.headers.get("location"), u);
      try {
        await assertPublic(loc.hostname);
        main = await grab(loc.toString());
        u = loc;
      } catch {
      }
    }
    html = (await main.text()).slice(0, 2e5);
  } catch {
    response.status(502).json({ error: `Couldn't reach ${u.origin}. Make sure it's live and public.` });
    return;
  }
  const H = (n) => main.headers.get(n);
  if (u.protocol !== "https:") findings.push({ category: "TLS", severity: "high", title: "No HTTPS", detail: "The site is served over plain http \u2014 credentials and cookies travel in cleartext." });
  else if (!H("strict-transport-security")) findings.push({ category: "TLS", severity: "medium", title: "Missing HSTS", detail: "No Strict-Transport-Security header \u2014 browsers can be downgraded to http before the redirect." });
  else passed.push("HSTS present");
  const hdr = [
    ["content-security-policy", "Content-Security-Policy", "high"],
    ["x-frame-options", "X-Frame-Options (clickjacking)", "medium"],
    ["x-content-type-options", "X-Content-Type-Options (MIME sniffing)", "low"],
    ["referrer-policy", "Referrer-Policy", "low"]
  ];
  for (const [k, label, sev] of hdr) {
    if (!H(k)) findings.push({ category: "Security headers", severity: sev, title: `Missing ${label}`, detail: `The ${label} response header is not set.` });
    else passed.push(`${label} set`);
  }
  if (H("x-powered-by") || /express|php|next\.js/i.test(H("server") || "")) findings.push({ category: "Security headers", severity: "low", title: "Stack banner leaked", detail: `Server reveals its stack (${H("x-powered-by") || H("server")}) \u2014 free recon for attackers.` });
  const sc = H("set-cookie") || "";
  if (sc) {
    const miss = ["HttpOnly", "Secure", "SameSite"].filter((f) => !new RegExp(f, "i").test(sc));
    if (miss.length) findings.push({ category: "Cookies", severity: "high", title: `Session cookie missing ${miss.join(", ")}`, detail: "A login cookie without these flags can be stolen via XSS, leaked over http, or used in CSRF." });
    else passed.push("Cookie flags hardened");
  }
  try {
    const c = await grab(u.toString(), { headers: { origin: "https://evil.example" } }, 6e3);
    const acao = c.headers.get("access-control-allow-origin");
    if (acao === "https://evil.example" || acao === "*" && (c.headers.get("access-control-allow-credentials") || "").toLowerCase() === "true")
      findings.push({ category: "CORS", severity: "high", title: "CORS reflects any origin", detail: "The server echoes an arbitrary Origin (a hostile site could read your logged-in users' data)." });
    else passed.push("CORS does not reflect hostile origin");
  } catch {
  }
  for (const path of ["/.env", "/.git/config", "/.git/HEAD", "/.env.local"]) {
    try {
      const r = await grab(new URL(path, u.origin).toString(), {}, 5e3);
      if (r.status === 200) {
        const ct = (r.headers.get("content-type") || "").toLowerCase();
        const body = (await r.text()).slice(0, 4e3);
        const looksReal = !ct.includes("text/html") && !body.trimStart().startsWith("<") && (/^\s*[A-Z0-9_]+\s*=/m.test(body) || /\[core\]/.test(body) || /^ref:\s/m.test(body) || /-----BEGIN/.test(body));
        if (looksReal) {
          findings.push({ category: "Secrets", severity: "critical", title: `Exposed ${path}`, detail: `${path} is publicly downloadable \u2014 it can leak credentials, keys, or your full git history.` });
          break;
        }
      }
    } catch {
    }
  }
  const seo = [
    [/<title[^>]*>\s*\S/i, "a real <title>", "medium"],
    [/<meta[^>]+name=["']description["'][^>]+content=["']\s*\S/i, "a meta description", "low"],
    [/<meta[^>]+name=["']viewport["']/i, "a mobile viewport tag", "medium"],
    [/<meta[^>]+property=["']og:title["']/i, "an Open Graph title (link previews)", "low"]
  ];
  for (const [re, label, sev] of seo) {
    if (re.test(html)) passed.push(label + " present");
    else findings.push({ category: "SEO", severity: sev, title: `Missing ${label}`, detail: `The page is missing ${label}.` });
  }
  const penalty = findings.reduce((s, f) => s + PENALTY[f.severity], 0);
  const score = Math.max(0, Math.min(100, 100 - penalty));
  const band = score >= 75 ? "green" : score >= 40 ? "yellow" : "red";
  const order = { critical: 0, high: 1, medium: 2, low: 3 };
  findings.sort((a, b) => order[a.severity] - order[b.severity]);
  response.status(200).json({
    ok: true,
    url: u.origin,
    score,
    band,
    passed: passed.length,
    summary: findings.length ? `Surface scan found ${findings.length} issue${findings.length === 1 ? "" : "s"} on ${u.host}.` : `No surface-level issues found on ${u.host} \u2014 nice. The deep checks still need your repo.`,
    findings,
    note: "This is the free 10-second surface scan (no code, no install). The deep audit \u2014 broken access control (IDOR), admin/RBAC, write-authz, and your actual code \u2014 runs free inside your own agent; your code never leaves your machine."
  });
}
export {
  handler as default
};
